
    
const TAILING_POINT_PER_BOOST = 1;
const SUBTRACT_POINT_PER_BOOST = 1;

const ONE_AI_WORM_DEBUG = true;
    
module.exports = {
    TAILING_POINT_PER_BOOST,
    SUBTRACT_POINT_PER_BOOST,
    ONE_AI_WORM_DEBUG
};