const MS_PER_FRAME = (1 / 60) * 1000;

const STAGE_SIZE = 30000;
const CREATE_PLAYER_SIZE_PER_STAGE = 0.6;
const CREATE_FOOD_SIZE_PER_STAGE = 0.8;

    
const TAILING_POINT_PER_BOOST = 1;
const SUBTRACT_POINT_PER_BOOST = 1;

const DEBUG_OPTION = {
    ALWAYS_CREATE_ROOM: false,
    AI_ONE: false,
    AI_SET_POS: null, //{ x: 15500, y: 15500 },
    USER_SET_POS: { x: 15000, y: 15000 },
};
    
module.exports = {
    MS_PER_FRAME,

    STAGE_SIZE, CREATE_PLAYER_SIZE_PER_STAGE, CREATE_FOOD_SIZE_PER_STAGE,

    TAILING_POINT_PER_BOOST, SUBTRACT_POINT_PER_BOOST,

    DEBUG_OPTION
};