const STAGE_SIZE = 30000;
const CREATE_PLAYER_SIZE_PER_STAGE = 0.6;
const CREATE_FOOD_SIZE_PER_STAGE = 0.8;

    
const TAILING_POINT_PER_BOOST = 1;
const SUBTRACT_POINT_PER_BOOST = 1;

const ONE_AI_WORM_DEBUG = false;
    
module.exports = {
    STAGE_SIZE, CREATE_PLAYER_SIZE_PER_STAGE, CREATE_FOOD_SIZE_PER_STAGE,

    TAILING_POINT_PER_BOOST, SUBTRACT_POINT_PER_BOOST,

    ONE_AI_WORM_DEBUG
};